### PR TITLE
test: Page.goto with 204

### LINKED ISSUE #441: test: Page.goto with 204
* [test: make sure page.goto works when subframes return 204.](https://github.com/GoogleChrome/puppeteer/commit/6eb6ce0ec96f8c888f274d21eb10ce79a7bb9b99) (#2361)
* [test: verify Page.goto fails when server returns 204](https://github.com/GoogleChrome/puppeteer/commit/b96815aa72063125fc1ab085dac5da59260d1fa2) (#2452)
* [fix(Page): fix page.goto to return Response when page pushes new state](https://github.com/GoogleChrome/puppeteer/commit/58c46680f37cd0b8fb0fa1805a6d79ad00464feb) (#2468)

### PR DESCRIPTION
**Pull request by Meir017**
closes #441

### CODE REVIEW

File: lib/PuppeteerSharp/Frame.cs [hunk 1]
```diff
@@ -580,6 +581,8 @@ internal void OnLifecycleEvent(string loaderId, string name)
         internal void Navigated(FramePayload framePayload)
         {
             Name = framePayload.Name ?? string.Empty;
+            // TODO(lushnikov): remove this once requestInterception has loaderId exposed.
```
Comment (kblok) [inline lib/PuppeteerSharp/Frame.cs]: I'd remove this comment. It's their TODO, not ours.
