### PR TITLE
Removed dynamic evaluate functions

### LINKED ISSUE #166: ERROR: PuppeteerSharp.MessageException : Protocol error (Runtime.callFunctionOn): Object reference chain is too long
when using `EvaluateExpressionAsync` or `EvaluateFunctionAsync` to return a `dynamic` object of something big the following exception is thrown:
PuppeteerSharp.MessageException : Protocol error (Runtime.callFunctionOn): Object reference chain is too long.

to reproduce this:
```cs
public class test
{
    [Fact]
    public async Task EvaluateBigObject()
    {
        using (var browser = await PuppeteerSharp.Puppeteer.LaunchAsync(TestConstants.DefaultBrowserOptions(), TestConstants.ChromiumRevision))
        using (var page = await browser.NewPageAsync())
        {
            var window = await page.EvaluateExpressionAsync("window"); // this throws
        }
    }
}
```

I suggest we delete the overloads that return `dynamic`.

whenever we don't care about the result we should use `EvaluateExpressionHandleAsync` or `EvaluateFunctionHandleAsync`

### PR DESCRIPTION
**Pull request by Meir017**
closes #166

### CODE REVIEW

File: lib/PuppeteerSharp/Page.cs [hunk 1]
```diff
@@ -156,13 +156,13 @@ private Page(Session client, Target target, FrameTree frameTree, bool ignoreHTTP
         public async Task<IEnumerable<ElementHandle>> GetElementsAsync(string selector)
             => await MainFrame.GetElementsAsync(selector);
 
-        public async Task<JSHandle> EvaluateExpressionHandle(string script)
+        public async Task<JSHandle> EvaluateExpressionHandleAsync(string script)
```
Comment (kblok) [inline lib/PuppeteerSharp/Page.cs]: Now you'll have to add XML Docs to the changed methods :joy:

File: lib/PuppeteerSharp.Tests/Frame/EvaluateTests.cs [hunk 2]
```diff
@@ -17,8 +17,8 @@ public class EvaluateTests : PuppeteerPageBaseTest
             var frame1 = Page.Frames.ElementAt(0);
             var frame2 = Page.Frames.ElementAt(1);
 
-            await frame1.EvaluateExpressionAsync("window.FOO = 'foo'");
-            await frame2.EvaluateExpressionAsync("window.FOO = 'bar'");
+            await frame1.EvaluateExpressionHandleAsync("window.FOO = 'foo'");
+            await frame2.EvaluateExpressionHandleAsync("window.FOO = 'bar'");
```
Comment (kblok) [inline lib/PuppeteerSharp.Tests/Frame/EvaluateTests.cs]: One thing I noticed across this PR (I won't mention this many times only here). Is that we're switching from `EvaluateExpression` to `EvaluateExpressionHandle` and that's not equivalent because the first one is disposing the handle as soon as possible.

Comment (kblok) [reply lib/PuppeteerSharp.Tests/Frame/EvaluateTests.cs]: Just a thought. How about if we get rid of `EvaluateExpressionHandleAsync` and we treat `EvaluateExpressionAsync<JSHandle>` in a special way?

Comment (Meir017) [reply lib/PuppeteerSharp.Tests/Frame/EvaluateTests.cs]: puppeteer has both a `evaluate` and `evaluateHandle` functions, and I prefer not to add **magic** to the function

Comment (kblok) [reply lib/PuppeteerSharp.Tests/Frame/EvaluateTests.cs]: @Meir017  👆 the first comment

**Comment by Meir017** [comment]
I think I found a solution - https://github.com/GoogleChrome/puppeteer/blob/v1.0.0/lib/ExecutionContext.js#L42
```js
const result = await handle.jsonValue().catch(error => undefined);
```
we should change the line
https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/ExecutionContext.cs#L33
```cs
var result = await handle.JsonValue<T>();
```
and make it catch the exception and return `null`

**Comment by kblok** [comment]
Make sense, we should also add the `EvaluateBigObject` test here.

**Comment by Meir017** [comment]
```
PuppeteerSharp.Tests.Puppeteer.PuppeteerLaunchTests.UserDataDirOption [FAIL]
System.Net.WebSockets.WebSocketException : The 'System.Net.WebSockets.InternalClientWebSocket' instance cannot be used for communication because it has been transitioned into the 'Aborted' state.
```

**Comment by kblok** [comment]
Conflicted @Meir017
