### PR TITLE
Process exit improvements

### LINKED ISSUE #128: Exception when Chrome fails to launch
If Chrome somehow fails to launch, the puppeteer fails to read the error message. Instead, I get the following exception:

```
Unhandled Exception: System.InvalidOperationException: Cannot mix synchronous and asynchronous operation on process stream.
at System.Diagnostics.Process.get_StandardError()
at PuppeteerSharp.Launcher.<>c__DisplayClass19_0.<WaitForEndpoint>b__0(Object sender, EventArgs e)
at System.Diagnostics.Process.OnExited()
at System.Diagnostics.Process.RaiseOnExited()
at System.Diagnostics.Process.CompletionCallback(Object context, Boolean wasSignaled)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

which occurs at this line: https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Launcher.cs#L241

I think it is because this line https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Launcher.cs#L287 is asynchronous, while the former is synchronous.

### PR DESCRIPTION
**Pull request by kblok**
* Check if the process is running before killing it.
* Grab the output from the output variable instead of trying to read the stream again.

Closes #128

### CODE REVIEW

File: lib/PuppeteerSharp/Launcher.cs [hunk 1]
```diff
@@ -156,6 +156,7 @@ public Launcher()
 
                 if (options.LogProcess)
                 {
+                    _processLoaded = true;
```
Comment (Meir017) [inline lib/PuppeteerSharp/Launcher.cs]: I think this should not be inside the `if` statement

File: lib/PuppeteerSharp/Launcher.cs [hunk 2]
```diff
@@ -236,10 +237,14 @@ private Task<string> WaitForEndpoint(Process chromeProcess, int timeout, bool du
...
+                if (_options.LogProcess && !_processLoaded)
+                {
+                    Console.WriteLine($"PROCESS COUNT: {Interlocked.Increment(ref _processCount)}");
+                }
+
                 CleanUp();
 
-                var error = chromeProcess.StandardError.ReadToEnd();
-                taskWrapper.SetException(new ChromeProcessException($"Failed to launch chrome! {error}"));
+                taskWrapper.SetException(new ChromeProcessException($"Failed to launch chrome! {output}"));
```
[the remark this answers is not in the document]
Comment (kblok) [reply lib/PuppeteerSharp/Launcher.cs]: `output` is being concatenated here https://github.com/kblok/puppeteer-sharp/blob/320fcc2876a54b9daac8c16160e818f41b3c7660/lib/PuppeteerSharp/Launcher.cs#L254

We first get the output and then the process exits.

File: lib/PuppeteerSharp/Launcher.cs (hunk 1 above)
Comment (kblok) [reply lib/PuppeteerSharp/Launcher.cs]: true.

Comment (kblok) [reply lib/PuppeteerSharp/Launcher.cs]: Done
