### PR TITLE
fix(browser): ensure first page is created when browser is launched

### LINKED ISSUE #471: fix(browser): ensure first page is created when browser is launched
https://github.com/kblok/puppeteer/pull/5/commits/9955a1e67391ab2be20bbf98eccaf9333726d936

### PR DESCRIPTION
**Pull request by Meir017**
closes #471

### CODE REVIEW

File: lib/PuppeteerSharp/Launcher.cs [hunk 1]
```diff
@@ -240,6 +242,26 @@ public static string GetTemporaryDirectory()
 
         #region Private methods
 
+        private async Task EnsureInitialPageAsync(Browser browser)
```
Comment (kblok) [inline lib/PuppeteerSharp/Launcher.cs]: This could be static.

File: lib/PuppeteerSharp/Launcher.cs [hunk 2]
```diff
@@ -240,6 +242,26 @@ public static string GetTemporaryDirectory()
...
+        {
+            // Wait for initial page target to be created.
+            if (browser.Targets().Any(target => target.Type == TargetType.Page))
+            {
+                return;
+            }
+            var initialPageComplection = new TaskCompletionSource<bool>();
```
Comment (kblok) [inline lib/PuppeteerSharp/Launcher.cs]: Complection? Typo?

**Comment by Meir017** [comment]
@kblok Done
